### ISSUE TITLE
Hidding the footer?

### ISSUE THREAD

**Issue by mpaul31** [MoonStorm/trNgGrid#61]
loving this directive but i must be missing something simple here. how do i configure the footer to be hidden by default?

**Comment by edicius6** [comment]
Exactly, but in case others might need the same answer, here is a solution:

**CSS:**
```css
table.hide-footer > tfoot {
    visibility: hidden;
    display: none;
}
```
**HTML:**
```html
<table tr-ng-grid class="hide-footer">
```
